version: '3.8'

services:
 
  web:
    build: .
    command: flask run --host=0.0.0.0 --port=5007
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
      DATABASE_URL:  postgresql://berkbirkan:brkbrkn840?@n4wwwo8:5432/bettipspro
    
    ports:
      - "5007:5007"
    volumes:
      - myimages:/app/assets