version: '3.8'

services:
 
  web:
    build: .
    command: flask run --host=0.0.0.0 --port=5017
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
      DATABASE_URL:  postgres://postgres:J6F9uzZ9au06Oj1KI7h3LxGFhlZx4isBpT91M01s4H6QlrA1xKgmfT86GUjwtbS6@tkso0s4g8g4wo0w0w8owggwo:5432/postgres
    
    ports:
      - "5017:5017"
    volumes:
      - myimages:/app/assets